name: CMake

on:
  push:
    branches: [ "dev/2.36.0" ]
  pull_request:
    branches: [ "dev/2.36.0" ]

jobs:
  build:
    strategy:
      matrix:
        buildType: [ Release, Debug ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.buildType }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.buildType }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.buildType }}
